name: Deploy Server

on:
    push:
        branches:
            - main

defaults:
    run:
        working-directory: ./websocket-server
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.AWS_PRIVATE_KEY }}
                  script_stop: true
                  script: |
                      export UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}
                      export CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
                      cd websocket-server
                      git pull
                      docker-compose down
                      docker-compose --project-name websocket-server up -d --build
